#!/bin/bash

app () {

    source ros.env


    
    build () {
        local mod=$1
        if [ -z "$mod" ]; then
            echo module name required
        fi
        docker build --no-cache $mod -t greentranslator/green-$mod
    }
    push () {
        local mod=$1
        if [ -z "$mod" ]; then
            echo module name required
        fi
        docker push greentranslator/green-$mod
    }
    db () {
        docker-compose run --service-ports neo4j
    }
    up () {
        docker-compose up
    }

    clean () {
        container=$(docker ps -a | awk '{ print $NF }' | grep _ros)
        docker stop $container
        docker rm $container
        docker rmi -f $(docker images | grep _ros | awk '{ print $1 }')
    }
    
    $*
}

echo $*
app $*
